# Generated by Django 2.2.9 on 2020-01-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('callePrincipal', models.CharField(max_length=200)),
                ('calleSecundaria', models.CharField(max_length=200)),
                ('numeroCasa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(choices=[('0', 'Masculino'), ('1', 'Femenino')], max_length=1)),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maestro_detalle.Direccion')),
            ],
        ),
    ]
